// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Skywardkite/loyalty-system/internal/handler/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function for the type MockStorage
func (_mock *MockStorage) AddOrder(ctx context.Context, userID int64, order string) error {
	ret := _mock.Called(ctx, userID, order)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, userID, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type MockStorage_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - order string
func (_e *MockStorage_Expecter) AddOrder(ctx interface{}, userID interface{}, order interface{}) *MockStorage_AddOrder_Call {
	return &MockStorage_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, userID, order)}
}

func (_c *MockStorage_AddOrder_Call) Run(run func(ctx context.Context, userID int64, order string)) *MockStorage_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_AddOrder_Call) Return(err error) *MockStorage_AddOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddOrder_Call) RunAndReturn(run func(ctx context.Context, userID int64, order string) error) *MockStorage_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// AddPointsToUser provides a mock function for the type MockStorage
func (_mock *MockStorage) AddPointsToUser(ctx context.Context, order dto.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for AddPointsToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddPointsToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPointsToUser'
type MockStorage_AddPointsToUser_Call struct {
	*mock.Call
}

// AddPointsToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - order dto.Order
func (_e *MockStorage_Expecter) AddPointsToUser(ctx interface{}, order interface{}) *MockStorage_AddPointsToUser_Call {
	return &MockStorage_AddPointsToUser_Call{Call: _e.mock.On("AddPointsToUser", ctx, order)}
}

func (_c *MockStorage_AddPointsToUser_Call) Run(run func(ctx context.Context, order dto.Order)) *MockStorage_AddPointsToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.Order
		if args[1] != nil {
			arg1 = args[1].(dto.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_AddPointsToUser_Call) Return(err error) *MockStorage_AddPointsToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddPointsToUser_Call) RunAndReturn(run func(ctx context.Context, order dto.Order) error) *MockStorage_AddPointsToUser_Call {
	_c.Call.Return(run)
	return _c
}

// AddWithdrawal provides a mock function for the type MockStorage
func (_mock *MockStorage) AddWithdrawal(ctx context.Context, userID int64, sum int64, orderID string) error {
	ret := _mock.Called(ctx, userID, sum, orderID)

	if len(ret) == 0 {
		panic("no return value specified for AddWithdrawal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = returnFunc(ctx, userID, sum, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWithdrawal'
type MockStorage_AddWithdrawal_Call struct {
	*mock.Call
}

// AddWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - sum int64
//   - orderID string
func (_e *MockStorage_Expecter) AddWithdrawal(ctx interface{}, userID interface{}, sum interface{}, orderID interface{}) *MockStorage_AddWithdrawal_Call {
	return &MockStorage_AddWithdrawal_Call{Call: _e.mock.On("AddWithdrawal", ctx, userID, sum, orderID)}
}

func (_c *MockStorage_AddWithdrawal_Call) Run(run func(ctx context.Context, userID int64, sum int64, orderID string)) *MockStorage_AddWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_AddWithdrawal_Call) Return(err error) *MockStorage_AddWithdrawal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddWithdrawal_Call) RunAndReturn(run func(ctx context.Context, userID int64, sum int64, orderID string) error) *MockStorage_AddWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateUser(ctx context.Context, login string, password string) (int64, error) {
	ret := _mock.Called(ctx, login, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, login, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, login, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, login, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - password string
func (_e *MockStorage_Expecter) CreateUser(ctx interface{}, login interface{}, password interface{}) *MockStorage_CreateUser_Call {
	return &MockStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, password)}
}

func (_c *MockStorage_CreateUser_Call) Run(run func(ctx context.Context, login string, password string)) *MockStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_CreateUser_Call) Return(n int64, err error) *MockStorage_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, login string, password string) (int64, error)) *MockStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function for the type MockStorage
func (_mock *MockStorage) GetBalance(ctx context.Context, userID int64) (*dto.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *dto.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*dto.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *dto.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockStorage_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetBalance(ctx interface{}, userID interface{}) *MockStorage_GetBalance_Call {
	return &MockStorage_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockStorage_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetBalance_Call) Return(account *dto.Account, err error) *MockStorage_GetBalance_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockStorage_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*dto.Account, error)) *MockStorage_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderUserByNumber provides a mock function for the type MockStorage
func (_mock *MockStorage) GetOrderUserByNumber(ctx context.Context, order string) (int64, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderUserByNumber")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetOrderUserByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderUserByNumber'
type MockStorage_GetOrderUserByNumber_Call struct {
	*mock.Call
}

// GetOrderUserByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - order string
func (_e *MockStorage_Expecter) GetOrderUserByNumber(ctx interface{}, order interface{}) *MockStorage_GetOrderUserByNumber_Call {
	return &MockStorage_GetOrderUserByNumber_Call{Call: _e.mock.On("GetOrderUserByNumber", ctx, order)}
}

func (_c *MockStorage_GetOrderUserByNumber_Call) Run(run func(ctx context.Context, order string)) *MockStorage_GetOrderUserByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetOrderUserByNumber_Call) Return(userID int64, err error) *MockStorage_GetOrderUserByNumber_Call {
	_c.Call.Return(userID, err)
	return _c
}

func (_c *MockStorage_GetOrderUserByNumber_Call) RunAndReturn(run func(ctx context.Context, order string) (int64, error)) *MockStorage_GetOrderUserByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUser provides a mock function for the type MockStorage
func (_mock *MockStorage) GetOrdersByUser(ctx context.Context, userID int64) ([]dto.OrderInfo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUser")
	}

	var r0 []dto.OrderInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]dto.OrderInfo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []dto.OrderInfo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.OrderInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetOrdersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUser'
type MockStorage_GetOrdersByUser_Call struct {
	*mock.Call
}

// GetOrdersByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetOrdersByUser(ctx interface{}, userID interface{}) *MockStorage_GetOrdersByUser_Call {
	return &MockStorage_GetOrdersByUser_Call{Call: _e.mock.On("GetOrdersByUser", ctx, userID)}
}

func (_c *MockStorage_GetOrdersByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetOrdersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetOrdersByUser_Call) Return(orderInfos []dto.OrderInfo, err error) *MockStorage_GetOrdersByUser_Call {
	_c.Call.Return(orderInfos, err)
	return _c
}

func (_c *MockStorage_GetOrdersByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]dto.OrderInfo, error)) *MockStorage_GetOrdersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessedOrders provides a mock function for the type MockStorage
func (_mock *MockStorage) GetUnprocessedOrders(ctx context.Context) ([]dto.Order, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessedOrders")
	}

	var r0 []dto.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.Order, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.Order); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetUnprocessedOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessedOrders'
type MockStorage_GetUnprocessedOrders_Call struct {
	*mock.Call
}

// GetUnprocessedOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetUnprocessedOrders(ctx interface{}) *MockStorage_GetUnprocessedOrders_Call {
	return &MockStorage_GetUnprocessedOrders_Call{Call: _e.mock.On("GetUnprocessedOrders", ctx)}
}

func (_c *MockStorage_GetUnprocessedOrders_Call) Run(run func(ctx context.Context)) *MockStorage_GetUnprocessedOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_GetUnprocessedOrders_Call) Return(orders []dto.Order, err error) *MockStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockStorage_GetUnprocessedOrders_Call) RunAndReturn(run func(ctx context.Context) ([]dto.Order, error)) *MockStorage_GetUnprocessedOrders_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function for the type MockStorage
func (_mock *MockStorage) GetUserByLogin(ctx context.Context, login string) (int64, string, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, string, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, login)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockStorage_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockStorage_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockStorage_GetUserByLogin_Call {
	return &MockStorage_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockStorage_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockStorage_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetUserByLogin_Call) Return(id int64, hashedPassword string, err error) *MockStorage_GetUserByLogin_Call {
	_c.Call.Return(id, hashedPassword, err)
	return _c
}

func (_c *MockStorage_GetUserByLogin_Call) RunAndReturn(run func(ctx context.Context, login string) (int64, string, error)) *MockStorage_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsByUser provides a mock function for the type MockStorage
func (_mock *MockStorage) GetWithdrawalsByUser(ctx context.Context, userID int64) ([]dto.Withdrawal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsByUser")
	}

	var r0 []dto.Withdrawal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]dto.Withdrawal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []dto.Withdrawal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Withdrawal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetWithdrawalsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsByUser'
type MockStorage_GetWithdrawalsByUser_Call struct {
	*mock.Call
}

// GetWithdrawalsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetWithdrawalsByUser(ctx interface{}, userID interface{}) *MockStorage_GetWithdrawalsByUser_Call {
	return &MockStorage_GetWithdrawalsByUser_Call{Call: _e.mock.On("GetWithdrawalsByUser", ctx, userID)}
}

func (_c *MockStorage_GetWithdrawalsByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetWithdrawalsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetWithdrawalsByUser_Call) Return(withdrawals []dto.Withdrawal, err error) *MockStorage_GetWithdrawalsByUser_Call {
	_c.Call.Return(withdrawals, err)
	return _c
}

func (_c *MockStorage_GetWithdrawalsByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]dto.Withdrawal, error)) *MockStorage_GetWithdrawalsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateOrderStatus(ctx context.Context, orderNumber string, status string) error {
	ret := _mock.Called(ctx, orderNumber, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, orderNumber, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockStorage_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - status string
func (_e *MockStorage_Expecter) UpdateOrderStatus(ctx interface{}, orderNumber interface{}, status interface{}) *MockStorage_UpdateOrderStatus_Call {
	return &MockStorage_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, orderNumber, status)}
}

func (_c *MockStorage_UpdateOrderStatus_Call) Run(run func(ctx context.Context, orderNumber string, status string)) *MockStorage_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateOrderStatus_Call) Return(err error) *MockStorage_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, orderNumber string, status string) error) *MockStorage_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function for the type MockStorage
func (_mock *MockStorage) UserExists(ctx context.Context, login string) (bool, error) {
	ret := _mock.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, login)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, login)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type MockStorage_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockStorage_Expecter) UserExists(ctx interface{}, login interface{}) *MockStorage_UserExists_Call {
	return &MockStorage_UserExists_Call{Call: _e.mock.On("UserExists", ctx, login)}
}

func (_c *MockStorage_UserExists_Call) Run(run func(ctx context.Context, login string)) *MockStorage_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UserExists_Call) Return(b bool, err error) *MockStorage_UserExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockStorage_UserExists_Call) RunAndReturn(run func(ctx context.Context, login string) (bool, error)) *MockStorage_UserExists_Call {
	_c.Call.Return(run)
	return _c
}
